### ISSUE TITLE
RG flow for XY model

### ISSUE THREAD

**Issue by diret47** [dartsushi/Loop-TNR_RGflow#1]
Hi Atsushi. I am wondering which file in this reprotory is about RG flow for XY model? In terms of your paper [Physical Review B 104 (16), 165132](https://arxiv.org/abs/2105.11460).

**Comment by dartsushi** [comment]
Hi! Sorry for the late reply.
I added a jupyter notebook on the XY model. The data is stored in /data_XY but you can also compute it from initialize_XY_twist module in Initialization.py.

Let me know if you have further questions!

**Comment by diret47** [comment]
Thanks for your response, and altruistic share.
